### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'profiler'

### ISSUE THREAD

**Issue by agenthong** [JiawangBian/sc_depth_pl#22]
Hi！

Thanks for sharing this great work! 

When I run the code, it occurs:

Traceback (most recent call last):
  File "../train.py", line 1, in <module>
    from pytorch_lightning import Trainer
  File "/home/hzc/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/hzc/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/home/hzc/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/callbacks/callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/home/hzc/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/utilities/__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/home/hzc/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 29, in <module>
    from pytorch_lightning.utilities.imports import _compare_version, _TORCHTEXT_LEGACY
  File "/home/hzc/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/utilities/imports.py", line 146, in <module>
    _KINETO_AVAILABLE = torch.profiler.kineto_available()
AttributeError: module 'torch' has no attribute 'profiler'

I install the env by requirements.txt. How can I solve this?

**Comment by JiawangBian** [comment]
It seems that your PyTorch is not correctly installed. Please go to "https://pytorch.org/" for installing it.

**Comment by agenthong** [comment]
Thank you for your reply.

I install pytorch 1.6.0 as the requirements.txt but pytorch-lightning requires torch>=1.7.*.

The error out as:
'pytorch-lightning 1.5.10 requires torch>=1.7.*, but you have torch 1.6.0+cu101 which is incompatible.
kornia 0.6.8 requires torch>=1.8.1, but you have torch 1.6.0+cu101 which is incompatible.'

**Comment by agenthong** [comment]
Hi， @JiawangBian!

I updated the PyTorch version and I solved this problem. Thanks!

When I run the training code, it asserts that there is no 'frame_index.txt'. But I download the NYU dataset via your link, I don't find 'frame_index.txt'. Can you point out where is 'frame_index.txt'? 

Thanks a lot!

**Comment by JiawangBian** [comment]
See "Train on Your Own Data" (2). This is optional.  You do not need it if you train without adding "--use_frame_index".

**Comment by agenthong** [comment]
Thanks again! @JiawangBian 

I met version problem as follow:

Traceback (most recent call last):
  File "./train.py", line 1, in <module>
    from pytorch_lightning import Trainer
  File "/home/hzc/anaconda3/envs/sc_pl/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/hzc/anaconda3/envs/sc_pl/lib/python3.8/site-packages/pytorch_lightning/callbacks/__init__.py", line 28, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "/home/hzc/anaconda3/envs/sc_pl/lib/python3.8/site-packages/pytorch_lightning/callbacks/pruning.py", line 31, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/home/hzc/anaconda3/envs/sc_pl/lib/python3.8/site-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/home/hzc/anaconda3/envs/sc_pl/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 46, in <module>
    from pytorch_lightning.loggers import Logger
  File "/home/hzc/anaconda3/envs/sc_pl/lib/python3.8/site-packages/pytorch_lightning/loggers/__init__.py", line 23, in <module>
    from pytorch_lightning.loggers.tensorboard import TensorBoardLogger
  File "/home/hzc/anaconda3/envs/sc_pl/lib/python3.8/site-packages/pytorch_lightning/loggers/tensorboard.py", line 26, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/hzc/anaconda3/envs/sc_pl/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
    LooseVersion = distutils.version.LooseVersion
AttributeError: module 'distutils' has no attribute 'version'

Which torch version do you use?

**Comment by JiawangBian** [comment]
I have updated the repo. Could you follow the latest README to install packages?
