### ISSUE TITLE
error  when I train my own data

### ISSUE THREAD

**Issue by wjlszhang** [JiawangBian/sc_depth_pl#27]
Hi, @JiawangBian 

When I train my own data by V3 model, I get below issue,  can you please guide me?

(sc_depth_env) [admin@localhost sc_depth_pl]$ **python train.py  --dataset_dir zylds --config configs/v3/th.txt --val_mode photo**
/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/torchvision/models/_utils.py:252: UserWarning: Accessing the model URLs via the internal dictionary of the module is deprecated since 0.13 and may be removed in the future. Please access them via the appropriate Weights Enum instead.
  warnings.warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
367 samples found for training
367 samples found for validation
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name      | Type     | Params
---------------------------------------
0 | depth_net | DepthNet | 14.8 M
1 | pose_net  | PoseNet  | 13.0 M
---------------------------------------
27.9 M    Trainable params
0         Non-trainable params
27.9 M    Total params
111.417   Total estimated model params size (MB)
Sanity Checking: 0it [00:00, ?it/s]/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:225: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 72 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Sanity Checking DataLoader 0:   0%|                                                                                                                                                                                  | 0/5 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 60, in <module>
    trainer.fit(system, dm)
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
    return self._run_train()
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1274, in _run_train
    self._run_sanity_check()
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1343, in _run_sanity_check
    val_loop.run()
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1704, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/admin/sc_depth_pl/SC_DepthV3.py", line 88, in validation_step
    tgt_img, ref_imgs, intrinsics = batch
ValueError: too many values to unpack (expected 3)

**Comment by JiawangBian** [comment]
As I am not aware of your data，could you try the dataset that I provided first？It should work well if your data format is the same as the provided dataset. Besides，I did not release the code for generating pseudo-depth. Will do that soon.

**Comment by wjlszhang** [comment]
I tried nyu data,  and the same issue happens.

**Comment by JiawangBian** [comment]
> I tried nyu data, and the same issue happens.

Have fixed. it is due to a dataloader issue.

**Comment by gabrielebaris** [comment]
@JiawangBian thanks for the very nice repo!
I am interested in training the network on my own dataset. I prepared the data as described in the README, but I am missing the pseudo-depth part. Can you provide some more info in this regard?
Thanks

**Comment by JiawangBian** [comment]
> @JiawangBian thanks for the very nice repo! I am interested in training the network on my own dataset. I prepared the data as described in the README, but I am missing the pseudo-depth part. Can you provide some more info in this regard? Thanks

I use the pretrained model (ResNext101) in https://github.com/aim-uofa/AdelaiDepth/tree/main/LeReS
You need to write some script to generate the pseudo-depth

**Comment by wjlszhang** [comment]
@JiawangBian thanks for fixing the issue,however, I tried my data, there was still but different issue reported in the same line.

(sc_depth_env) [admin@localhost sc_depth_pl]$ python train.py  --dataset_dir zylds --config configs/v3/th.txt --val_mode photo
/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/torchvision/models/_utils.py:252: UserWarning: Accessing the model URLs via the internal dictionary of the module is deprecated since 0.13 and may be removed in the future. Please access them via the appropriate Weights Enum instead.
  warnings.warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
2138 samples found for training
2138 samples found for validation
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [1]

  | Name      | Type     | Params
---------------------------------------
0 | depth_net | DepthNet | 14.8 M
1 | pose_net  | PoseNet  | 13.0 M
---------------------------------------
27.9 M    Trainable params
0         Non-trainable params
27.9 M    Total params
111.417   Total estimated model params size (MB)
Sanity Checking DataLoader 0:   0%|                                                                                                                                                                                 | 0/5 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 60, in <module>
    trainer.fit(system, dm)
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
    return self._run_train()
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1274, in _run_train
    self._run_sanity_check()
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1343, in _run_sanity_check
    val_loop.run()
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1704, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/admin/sc_depth_pl/SC_DepthV3.py", line 90, in validation_step
    tgt_depth = self.depth_net(tgt_img)
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/admin/sc_depth_pl/models/DepthNet.py", line 134, in forward
    outputs = self.decoder(features)
  File "/home/admin/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/admin/sc_depth_pl/models/DepthNet.py", line 108, in forward
    x = torch.cat(x, 1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 136 but got size 135 for tensor number 1 in the list.


The size of my own data is set as below in config.py and the dataset_name is set in my cofiguration th.txt file

    elif dataset_name == 'th':
        training_size = [1080, 1920]
