### ISSUE TITLE
Error training V3 with its own dataset

### ISSUE THREAD

**Issue by countlesswu** [JiawangBian/sc_depth_pl#42]
Thank you for your excellent work.
I built my dataset in your format, with gt, and also added pseudo-depth, all image sizes are **256*256.**
My dataset is a number of pictures of endoscopes, with 500 pictures in the validation set and 2000 pictures in the training set.
like this picture:
![image_0001](https://user-images.githubusercontent.com/53824506/210045157-f701e342-4422-49b8-99ec-c93f98317c05.jpg)
Enter the command：CUDA_VISIBLE_DEVICES=0 python train.py --config /home/ubuntu/wl/sc_depth_pl-master/configs/v3/nyu.txt --dataset_dir /home/ubuntu/data0/dataset_endo_colon
get error：/home/ubuntu/miniconda3/envs/sc_depth_env/lib/python3.8/site-packages/torchvision/models/_utils.py:252: UserWarning: Accessing the model URLs via the internal dictionary of the module is deprecated since 0.13 and will be removed in 0.15. Please access them via the appropriate Weights Enum instead.
  warnings.warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
`Trainer(limit_val_batches=1.0)` was configured so 100% of the batches will be used..
1998 samples found for training
500 samples found for validation
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name      | Type     | Params
---------------------------------------
0 | depth_net | DepthNet | 14.8 M
1 | pose_net  | PoseNet  | 13.0 M
---------------------------------------
27.9 M    Trainable params
0         Non-trainable params
27.9 M    Total params
111.417   Total estimated model params size (MB)
Sanity Checking DataLoader 0:   0%|                                                                     | 0/5 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 60, in <module>
    trainer.fit(system, dm)
  File "/home/ubuntu/miniconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/home/ubuntu/miniconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/ubuntu/miniconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/home/ubuntu/miniconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
    return self._run_train()
  File "/home/ubuntu/miniconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1274, in _run_train
    self._run_sanity_check()
  File "/home/ubuntu/miniconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1343, in _run_sanity_check
    val_loop.run()
  File "/home/ubuntu/miniconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/ubuntu/miniconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/ubuntu/miniconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/home/ubuntu/miniconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1704, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/sc_depth_env/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/ubuntu/wl/sc_depth_pl-master/SC_DepthV3.py", line 82, in validation_step
    errs = LossF.compute_errors(gt_depth, tgt_depth, self.hparams.hparams.dataset_name)
  File "/home/ubuntu/miniconda3/envs/sc_depth_env/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/wl/sc_depth_pl-master/losses/loss_functions.py", line 193, in compute_errors
    batch_size, h, w = gt.size()
ValueError: too many values to unpack (expected 3)

I want to ask you a few questions,：
Are 2000 training sets and 500 validation sets too few? 
Is sc-depth-V3 suitable for endoscopic Settings (like inside the large intestine)? 
In config, I can only choose bonn, ddad, kitti_raw, nyu, and tum, etc., but which one should I choose when I use my own data set? My own data set image size is **256*256**. Should I modify my image size to fit one of the five options above? But I don't know the specific size of these five types of pictures. I guess the above error is caused by the mismatch between the size of my data set and the nyu data set. I am looking forward to your reply

**Comment by countlesswu** [comment]
I have solved it !!
thanks
