### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by doubleZ0108** [JiawangBian/sc_depth_pl#51]
I setup the env as the guidance, but when I run `sh scripts/run_inference.sh` I got the following error
```
(sc_depth_env) [root@sc_depth_pl]# sh scripts/run_inference.sh 
Traceback (most recent call last):
  File "inference.py", line 10, in <module>
    from SC_Depth import SC_Depth
  File ".../Models/sc_depth_pl/SC_Depth.py", line 8, in <module>
    from visualization import *
  File ".../Models/sc_depth_pl/visualization.py", line 1, in <module>
    import cv2
  File "/data/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/data/anaconda3/envs/sc_depth_env/lib/python3.8/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/data/anaconda3/envs/sc_depth_env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dlopen: cannot load any more object with static TLS
```

**Comment by doubleZ0108** [comment]
I have solved the problem by following the [issue](https://github.com/tensorflow/models/issues/523) reported in TensorFlow.
And this is a reminder for peers meeting the same problem:
‼ You should put all `from visualization import *` and `import cv2` before `import torch`.
See carefully in `SC_DepthVx.py`, `visualization.py`, `custom_transforms.py`, etc.
