### ISSUE TITLE
not able to do inference on demo(weights issue) got an unexpected keyword argument 'weights'

### ISSUE THREAD

**Issue by brooklynsdeath** [JiawangBian/sc_depth_pl#55]
run this command 
python3 inference.py --config configs/v3/nyu.txt --input_dir demo/input/ --output_dir demo/output/ --ckpt_path ckpts/nyu_scv3/epoch=93-val_loss=0.1384.ckpt --save-vis --save-depth

error
Traceback (most recent call last):
  File "inference.py", line 83, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "inference.py", line 28, in main
    system = SC_DepthV3(hparams)
  File "/docker_shared/sc_depth_pl/SC_DepthV3.py", line 18, in __init__
    self.depth_net = DepthNet(self.hparams.hparams.resnet_layers)
  File "/docker_shared/sc_depth_pl/models/DepthNet.py", line 126, in __init__
    num_layers=num_layers, pretrained=pretrained, num_input_images=1)
  File "/docker_shared/sc_depth_pl/models/resnet_encoder.py", line 91, in __init__
    self.encoder = resnets[num_layers](weights="IMAGENET1K_V1")
  File "/usr/local/lib/python3.7/dist-packages/torchvision/models/resnet.py", line 277, in resnet18
    **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/models/resnet.py", line 260, in _resnet
    model = ResNet(block, layers, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'weights'**

**Comment by JiawangBian** [comment]
it is due to pytorch version issue. you may change "self.encoder = resnets[num_layers](weights="IMAGENET1K_V1")" to "                self.encoder = resnets[num_layers](True)" to fit  your pytorch version. 

https://github.com/JiawangBian/sc_depth_pl/blob/308699c5b13c86f51eae4616ab5b8818f1116623/models/resnet_encoder.py#L90
