### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by illuosion** [JiawangBian/sc_depth_pl#69]
Hello, I came across the problem below when I trained V3 on **1 A800 GPU**
My env is
**torch==1.12.0-cu113**
Exception has occurred: AttributeError
Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/iCompute/envs/sc_depth_env/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/iCompute/envs/sc_depth_env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/iCompute/envs/sc_depth_env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/fyy/sc_depth_pl-master/datasets/validation_folders.py", line 57, in __getitem__
    imread(self.depth[index]).astype(np.float32)).float()/5000
  File "/usr/local/iCompute/envs/sc_depth_env/lib/python3.8/site-packages/imageio/__init__.py", line 97, in imread
    return imread_v2(uri, format=format, **kwargs)
  File "/usr/local/iCompute/envs/sc_depth_env/lib/python3.8/site-packages/imageio/v2.py", line 360, in imread
    result = file.read(index=0, **kwargs)
  File "/usr/local/iCompute/envs/sc_depth_env/lib/python3.8/site-packages/imageio/plugins/pillow.py", line 231, in read
    image = self._apply_transforms(
  File "/usr/local/iCompute/envs/sc_depth_env/lib/python3.8/site-packages/imageio/plugins/pillow.py", line 312, in _apply_transforms
    image.mode = desired_mode
AttributeError: can't set attribute

**Comment by illuosion** [comment]
I have sovled this, seems like the latest version of imageio is not suitable
